package org.jwt.oauth.AuthenticationServer.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.List;

/**
 * Represents the user data stored in MongoDB.
 */
@Data
@NoArgsConstructor
@Document(collection = "user_details")
public class User {
    /**
     * Primary key, automatically generated by MongoDB.
     */
    @Id
    private ObjectId userId;

    /**
     * Unique username for login/authentication.
     */
    @NonNull
    @Indexed(unique = true)
    private String userName;

    /**
     * Encrypted password of the user.
     */
    @NonNull
    private String passWord;

    /**
     * Optional email field for contact or notifications.
     */
    private String userEmail;

    /**
     * Defines user privileges. Enum list to support multiple roles.
     */
    private List<UserRoles> userRoles;
}

